export enum EventAlertEnum {
    UPDATE_SPECIFIC_STATUS,
    UPDATE_REPLY_STATUS,
    UPDATE_FOLLOWING,
    UPDATE_FOLLOWERS,
    UPDATE_FOLLOWING_AND_FOLLOWERS,
    UPDATE_STATUS_FORM_TEXT,
    REMOVE_STATUS,
}