export * from './admin/admin.page';
export * from './app/app.page';
export * from './home/home.page';
export * from './localfeed/localfeed.page';
export * from './login/login.page';
export * from './notifications/notifications.page';
export * from './profile/profile.page';
export * from './register/register.page';
export * from './searchresults/searchresults.page';